import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import {
  TOKEN_PROGRAM_ID,
  createMint,
  createAccount,
  mintTo,
  getAccount,
} from "@solana/spl-token";
import { Keypair, PublicKey, SystemProgram, Transaction } from "@solana/web3.js";
import { createHash } from "crypto";
import { expect } from "chai";

// Program type is generated by `anchor build` into target/types/escrow.
// Using `any` here keeps this file independent of that build step so it can
// be read/reviewed without running Anchor first.
type EscrowProgram = Program<any>;

describe("escrow", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const program = anchor.workspace.Escrow as EscrowProgram;
  const connection = provider.connection;

  const decimals = 2; // matches CONTRACTS.md: integer minor units (cents)

  let mint: PublicKey;
  let buyer: Keypair;
  let supplier: Keypair;
  let buyerAta: PublicKey;
  let supplierAta: PublicKey;

  async function airdrop(pubkey: PublicKey, sol = 2) {
    const sig = await connection.requestAirdrop(pubkey, sol * anchor.web3.LAMPORTS_PER_SOL);
    await connection.confirmTransaction(sig, "confirmed");
  }

  function orderIdHash(orderRef: string): Buffer {
    return createHash("sha256").update(orderRef).digest();
  }

  function escrowPda(buyerKey: PublicKey, hash: Buffer) {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("escrow"), buyerKey.toBuffer(), hash],
      program.programId
    );
  }

  function vaultPda(escrow: PublicKey) {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), escrow.toBuffer()],
      program.programId
    );
  }

  async function fundBuyer(amount: number) {
    await mintTo(connection, buyer, mint, buyerAta, buyer, amount);
  }

  async function newEscrow(orderRef: string, amount: number) {
    const hash = orderIdHash(orderRef);
    const [escrow] = escrowPda(buyer.publicKey, hash);
    const [vault] = vaultPda(escrow);
    const termsHash = createHash("sha256").update(orderRef + ":terms").digest();

    await program.methods
      .fund(Array.from(hash), new BN(amount), supplier.publicKey, Array.from(termsHash))
      .accounts({
        escrow,
        vault,
        mint,
        buyerTokenAccount: buyerAta,
        buyer: buyer.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .signers([buyer])
      .rpc();

    return { hash, escrow, vault };
  }

  before(async () => {
    buyer = Keypair.generate();
    supplier = Keypair.generate();
    await airdrop(buyer.publicKey);
    await airdrop(supplier.publicKey);

    const mintAuthority = Keypair.generate();
    await airdrop(mintAuthority.publicKey, 1);
    mint = await createMint(connection, mintAuthority, mintAuthority.publicKey, null, decimals);

    buyerAta = await createAccount(connection, buyer, mint, buyer.publicKey);
    supplierAta = await createAccount(connection, supplier, mint, supplier.publicKey);

    await mintTo(connection, mintAuthority, mint, buyerAta, mintAuthority, 100_000);
  });

  it("happy path: fund -> accept_all pays the supplier in full", async () => {
    const amount = 3000; // $30.00 at 2 decimals
    const { escrow, vault } = await newEscrow("PO-HAPPY-1", amount);

    await program.methods
      .acceptAll()
      .accounts({
        escrow,
        vault,
        supplierTokenAccount: supplierAta,
        buyer: buyer.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([buyer])
      .rpc();

    const supplierAccount = await getAccount(connection, supplierAta);
    expect(Number(supplierAccount.amount)).to.equal(amount);

    const vaultAccount = await getAccount(connection, vault);
    expect(Number(vaultAccount.amount)).to.equal(0);

    const escrowState = await program.account.escrow.fetch(escrow);
    expect(escrowState.status).to.deep.equal({ released: {} });
  });

  it("demo split: $30 order, claim $10, $20 released now, settle refunds the $10", async () => {
    const total = 3000; // $30.00
    const accepted = 2000; // $20.00
    const claimed = 1000; // $10.00
    const { escrow, vault } = await newEscrow("PO-DEMO-SPLIT", total);

    const supplierBefore = (await getAccount(connection, supplierAta)).amount;

    await program.methods
      .claim(new BN(accepted), new BN(claimed))
      .accounts({
        escrow,
        vault,
        supplierTokenAccount: supplierAta,
        buyer: buyer.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([buyer])
      .rpc();

    const supplierAfterClaim = await getAccount(connection, supplierAta);
    expect(Number(supplierAfterClaim.amount) - Number(supplierBefore)).to.equal(accepted);

    const midState = await program.account.escrow.fetch(escrow);
    expect(midState.status).to.deep.equal({ claimed: {} });
    expect(Number(midState.claimedAmount)).to.equal(claimed);

    // Both buyer AND supplier must sign settle().
    await program.methods
      .settle(new BN(0), new BN(claimed))
      .accounts({
        escrow,
        vault,
        supplierTokenAccount: supplierAta,
        buyerTokenAccount: buyerAta,
        buyer: buyer.publicKey,
        supplier: supplier.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([buyer, supplier])
      .rpc();

    const finalState = await program.account.escrow.fetch(escrow);
    expect(finalState.status).to.deep.equal({ settled: {} });
    expect(Number(finalState.claimedAmount)).to.equal(0);

    const vaultAccount = await getAccount(connection, vault);
    expect(Number(vaultAccount.amount)).to.equal(0);
  });

  it("must fail: a non-buyer signer cannot release funds", async () => {
    const { escrow, vault } = await newEscrow("PO-WRONG-SIGNER", 1000);
    const attacker = Keypair.generate();
    await airdrop(attacker.publicKey, 1);

    let threw = false;
    try {
      await program.methods
        .acceptAll()
        .accounts({
          escrow,
          vault,
          supplierTokenAccount: supplierAta,
          buyer: attacker.publicKey, // not the stored buyer
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([attacker])
        .rpc();
    } catch (err) {
      threw = true;
    }
    expect(threw, "expected accept_all to reject a non-buyer signer").to.be.true;
  });

  it("must fail: settle amounts that don't sum to the locked amount", async () => {
    const { escrow, vault } = await newEscrow("PO-BAD-SUM", 1000);

    await program.methods
      .claim(new BN(400), new BN(600))
      .accounts({
        escrow,
        vault,
        supplierTokenAccount: supplierAta,
        buyer: buyer.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([buyer])
      .rpc();

    let threw = false;
    try {
      await program.methods
        .settle(new BN(100), new BN(400)) // sums to 500, not the locked 600
        .accounts({
          escrow,
          vault,
          supplierTokenAccount: supplierAta,
          buyerTokenAccount: buyerAta,
          buyer: buyer.publicKey,
          supplier: supplier.publicKey,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([buyer, supplier])
        .rpc();
    } catch (err) {
      threw = true;
    }
    expect(threw, "expected settle to reject a mismatched split").to.be.true;
  });

  it("must fail: settle without the supplier's signature", async () => {
    const { escrow, vault } = await newEscrow("PO-ONE-SIG", 1000);

    await program.methods
      .claim(new BN(0), new BN(1000))
      .accounts({
        escrow,
        vault,
        supplierTokenAccount: supplierAta,
        buyer: buyer.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([buyer])
      .rpc();

    let threw = false;
    try {
      // Only the buyer signs; the instruction requires supplier as a Signer too.
      await program.methods
        .settle(new BN(0), new BN(1000))
        .accounts({
          escrow,
          vault,
          supplierTokenAccount: supplierAta,
          buyerTokenAccount: buyerAta,
          buyer: buyer.publicKey,
          supplier: supplier.publicKey,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([buyer])
        .rpc();
    } catch (err) {
      threw = true;
    }
    expect(threw, "expected settle to reject a missing supplier signature").to.be.true;
  });

  it("must fail: a changed destination token account is rejected", async () => {
    const { escrow, vault } = await newEscrow("PO-CHANGED-DEST", 1000);
    const attacker = Keypair.generate();
    await airdrop(attacker.publicKey, 1);
    const attackerAta = await createAccount(connection, attacker, mint, attacker.publicKey);

    let threw = false;
    try {
      await program.methods
        .acceptAll()
        .accounts({
          escrow,
          vault,
          supplierTokenAccount: attackerAta, // not the stored supplier's account
          buyer: buyer.publicKey,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([buyer])
        .rpc();
    } catch (err) {
      threw = true;
    }
    expect(threw, "expected accept_all to reject a changed destination").to.be.true;
  });

  it("must fail: a second payout on an already-released escrow", async () => {
    const { escrow, vault } = await newEscrow("PO-DOUBLE-PAYOUT", 1000);

    await program.methods
      .acceptAll()
      .accounts({
        escrow,
        vault,
        supplierTokenAccount: supplierAta,
        buyer: buyer.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([buyer])
      .rpc();

    let threw = false;
    try {
      await program.methods
        .acceptAll()
        .accounts({
          escrow,
          vault,
          supplierTokenAccount: supplierAta,
          buyer: buyer.publicKey,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([buyer])
        .rpc();
    } catch (err) {
      threw = true;
    }
    expect(threw, "expected a second accept_all to fail").to.be.true;
  });
});
